[book]
title = "The Lime Programming Language 日本語版"
author = "Lime Contributors"
language = "ja"

[output.html]
additional-css = ["ferris.css", "theme/2018-edition.css", "theme/em-to-bold.css"]
additional-js = ["ferris.js"]
